apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mindie-ms-pvc
  namespace: model-engine
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sc-mindie-ms
  resources:
    requests:
      storage: 10Gi
